apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commandsservice
  template:
    metadata:
      labels:
        app: commandsservice
    spec:
      containers:
        - name: commandsservice
          image: kayceecode/commandsservice
---
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-serv
spec:
  type: ClusterIP
  selector:
    app: commandsservice
  ports:
  - name: commandsservice
    port: 80
<<<<<<< HEAD
    targetPort: 80
=======
    targetPort: 80
>>>>>>> 620a9a3215708d96c78f0fa48610ee89b5788845
